Form/Type/LocaleType.php
<?php declare(strict_types=1);
/**
 * @author    Igor Nikolaev <igor.sv.n@gmail.com>
 * @copyright Copyright (c) 2016-2019, Darvin Studio
 * @link      https://www.darvin-studio.ru
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Darvin\AdminBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Locale form type
 */
class LocaleType extends AbstractType
{
    /**
     * @var string[]
     */
    private $locales;

    /**
     * @param string[] $locales Locales
     */
    public function __construct(array $locales)
    {
        $this->locales = $locales;
    }

    /**
     * {@inheritDoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'choices' => $this->buildChoices(),
        ]);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent(): string
    {
        return ChoiceType::class;
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockPrefix(): string
    {
        return 'darvin_admin_locale';
    }

    /**
     * @return array
     */
    private function buildChoices(): array
    {
        $choices = [];

        foreach ($this->locales as $locale) {
            $choices['locale.'.$locale] = $locale;
        }

        return $choices;
    }
}

Form/Type/Security/Permissions/AdministratorPermissionsType.php
<?php
/**
 * @author    Igor Nikolaev <igor.sv.n@gmail.com>
 * @copyright Copyright (c) 2015, Darvin Studio
 * @link      https://www.darvin-studio.ru
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Darvin\AdminBundle\Form\Type\Security\Permissions;

use Darvin\AdminBundle\Security\Permissions\AdministratorPermissions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Administrator permissions form type
 */
class AdministratorPermissionsType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('administratorId', 'hidden', array(
                'label' => false,
            ))
            ->add('permissions', 'collection', array(
                'label'   => false,
                'type'    => 'checkbox',
                'options' => array(
                    'required' => false,
                ),
            ));
    }

    /**
     * {@inheritdoc}
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $permissionsField = $view->children['permissions'];

        /** @var \Symfony\Component\Form\FormView $child */
        foreach ($permissionsField->children as $name => $child) {
            $child->vars['label'] = 'security.permission.'.$name;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => AdministratorPermissions::ADMINISTRATOR_PERMISSIONS_CLASS,
            'intention'  => md5(__FILE__.$this->getName()),
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'darvin_admin_security_administrator_permissions';
    }
}

Controller/Security/LoginController.php
<?php declare(strict_types=1);
/**
 * @author    Igor Nikolaev <igor.sv.n@gmail.com>
 * @copyright Copyright (c) 2015-2019, Darvin Studio
 * @link      https://www.darvin-studio.ru
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Darvin\AdminBundle\Controller\Security;

use Darvin\UserBundle\Form\Factory\SecurityFormFactoryInterface;
use Darvin\UserBundle\Form\Renderer\SecurityFormRendererInterface;
use Darvin\Utils\HttpFoundation\AjaxResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;

/**
 * Security login controller
 */
class LoginController
{
    /**
     * @var \Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    /**
     * @var \Darvin\UserBundle\Form\Factory\SecurityFormFactoryInterface
     */
    private $formFactory;

    /**
     * @var \Darvin\UserBundle\Form\Renderer\SecurityFormRendererInterface
     */
    private $formRenderer;

    /**
     * @var \Symfony\Component\Routing\RouterInterface
     */
    private $router;

    /**
     * @param \Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface $authorizationChecker Authorization checker
     * @param \Darvin\UserBundle\Form\Factory\SecurityFormFactoryInterface                 $formFactory          Security form factory
     * @param \Darvin\UserBundle\Form\Renderer\SecurityFormRendererInterface               $formRenderer         Security form renderer
     * @param \Symfony\Component\Routing\RouterInterface                                   $router               Router
     */
    public function __construct(
        AuthorizationCheckerInterface $authorizationChecker,
        SecurityFormFactoryInterface $formFactory,
        SecurityFormRendererInterface $formRenderer,
        RouterInterface $router
    ) {
        $this->authorizationChecker = $authorizationChecker;
        $this->formFactory = $formFactory;
        $this->formRenderer = $formRenderer;
        $this->router = $router;
    }

    /**
     * @param \Symfony\Component\HttpFoundation\Request $request Request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Request $request): Response
    {
        if ($this->authorizationChecker->isGranted(AuthenticatedVoter::IS_AUTHENTICATED_REMEMBERED)) {
            return new RedirectResponse($this->router->generate('darvin_admin_homepage'));
        }

        $html = $this->formRenderer->renderLoginForm(
            $this->formFactory->createLoginForm([
                'action' => $this->router->generate('darvin_admin_security_login_check'),
            ]),
            $request->isXmlHttpRequest(),
            sprintf('@DarvinAdmin/security/%slogin.html.twig', $request->isXmlHttpRequest() ? '_' : '')
        );

        if ($request->isXmlHttpRequest()) {
            return new AjaxResponse($html);
        }

        return new Response($html);
    }
}

Resources/views/security/_login.html.twig
{% form_theme form _self %}

{% trans_default_domain 'admin' %}

{% block form_errors %}
    {% if errors is defined and errors|length > 0 %}
        <div class="form-item__error js-form-errors">
            <ul>
                {% for error in errors %}
                    <li>{{ error.message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

{% block __username_row %}
    {% if form.parent %}
        <div class="form-item -login">
            <div class="form-item__field">
                <div class="form-item__input" data-type="small">
                    {{ form_widget(form, {'attr': {'data-input': '', 'placeholder': label}}) }}
                </div>
                {{ form_errors(form) }}
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block __password_row %}
    {% if form.parent %}
        <div class="form-item -password">
            <div class="form-item__field">
                <div class="form-item__input js-btn-password-show" data-type="small">
                    {{ form_widget(form, {'attr': {'data-input': '', 'placeholder': label}}) }}
                    <button data-btn-password-show type="button" title="{% trans %}form.password.show{% endtrans %}">&nbsp;</button>
                </div>
                {{ form_errors(form) }}
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block __remember_me_row %}
    {% if form.parent %}
        {{ form_widget(form, {'attr': {'style': 'display: none;'}}) }}
        {{ form_errors(form) }}
    {% endif %}
{% endblock %}

{{ form_start(form, {'attr': {'class': 'js-form'}}) }}
<div class="form-login">
    {{ form_widget(form) }}
    <button class="form-login__btn-login" type="submit">{% trans %}security.action.login.submit{% endtrans %}</button>
</div>
{{ form_end(form) }}

Resources/views/security/login.html.twig
{% extends '@DarvinAdmin/layout.html.twig' %}

{% trans_default_domain 'admin' %}

{% block extra_stylesheets %}{% endblock %}

{% block body_class %}login-page{% endblock %}

{% block body %}
    <div class="login-wrapper">
        <div class="login-wrapper__container">
            <div class="login-wrapper__logo">
                {% if darvin_admin.logo %}
                    <img src="{{ asset(darvin_admin.logo) }}" alt="">
                {% else %}
                    <div class="logo">

                        {% include '@DarvinAdmin/logo.html.twig' %}

                    </div>
                {% endif %}
            </div>
            <div class="login-wrapper__form">
                <p class="login-wrapper__tilte">{% trans %}security.action.login.title{% endtrans %}</p>

                {% include '@DarvinAdmin/security/_login.html.twig' %}

                <div class="login-wrapper__links">
                    <a class="login-wrapper__link-auth"
                       href="{{ path('darvin_admin_security_darvin_auth_login', {'service': 'darvin_auth_admin'}) }}">
                        {% trans %}security.action.login.darvin_auth{% endtrans %}
                    </a>
{#                    <a class="login-wrapper__link-password" href="">Забыли пароль?</a>#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascripts %}{% endblock %}